---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
  ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: heetvasani1/scientificcalculator
        tag: latest
        source: pull

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name Calculator heetvasani1/scientificcalculator