---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
  ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: heetvasani1/scientificcalculatorr:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker create -it --name Calculator heetvasani1/scientificcalculator